// current machine
export const RESET_INITIAL_CURRENT_MACHINE = 'RESET_INITIAL_CURRENT_MACHINE';
export const SET_CURRENT_MACHINE = 'SET_CURRENT_MACHINE';
export const SET_ADDRESS_OF_CURRENT_MACHINE = 'SET_ADDRESS_OF_CURRENT_MACHINE';
export const SET_PORT_OF_CURRENT_MACHINE = 'SET_PORT_OF_CURRENT_MACHINE';
export const SET_LOGIN_OF_CURRENT_MACHINE = 'SET_LOGIN_OF_CURRENT_MACHINE';
export const SET_PASSWORD_OF_CURRENT_MACHINE = 'SET_PASSWORD_OF_CURRENT_MACHINE';
export const SET_COMMAND_TO_CURRENT_MACHINE = 'SET_COMMAND_TO_CURRENT_MACHINE';

//terminal
export const PUSH_STORY = 'PUSH_STORY';
export const RESET_TERMINAL = 'RESET_TERMINALs';

// currentNetwork
export const SET_SCAN_RANGE = 'SET_SCAN_RANGE';
export const SET_MACHINES_DATA = 'SET_MACHINES_DATA';
